### PR TITLE
Update from upstream, fix build on Linux 6.2

### LINKED ISSUE #19: Can not be built with recent kernel like 6.2.2
**Distribution (run `cat /etc/os-release`):**
 Debian 12 with kernel 6.2.2
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Can not be built with recent kernel like 6.2.2

**Issue/Bug Description:**

several -Werror=incompatible-pointer-types during make

**Steps to reproduce (if you know):**
pull repo
cd repo
make

### PR DESCRIPTION
**Pull request by jackpot51**
Fixes #19, although upstream driver should be used

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Confirmed this fixes building on kernel 6.2. The module still works properly; in particular (looking at the diff), I still have battery charge thresholds on an Open Firmware system.

This does seem to break building on kernel 6.1/6.0, it looks like due to `static int system76_remove(...` changing to `static void system76_remove(...`:

```
make -C "/lib/modules/6.1.11-76060111-generic/build" M="/home/system76/system76-acpi-dkms" modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.11-76060111-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  You are using:           gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  CC [M]  /home/system76/system76-acpi-dkms/system76_acpi.o
/home/system76/system76-acpi-dkms/system76_acpi.c:788:27: error: initialization of ‘int (*)(struct acpi_device *)’ from incompatible pointer type ‘void (*)(struct acpi_device *)’ [-Werror=incompatible-pointer-types]
  788 |                 .remove = system76_remove,
      |                           ^~~~~~~~~~~~~~~
/home/system76/system76-acpi-dkms/system76_acpi.c:788:27: note: (near initialization for ‘system76_driver.ops.remove’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:250: /home/system76/system76-acpi-dkms/system76_acpi.o] Error 1
make[1]: *** [Makefile:2011: /home/system76/system76-acpi-dkms] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.11-76060111-generic'
make: *** [Makefile:5: all] Error 2
```

Approving assuming we only need to target the current kernel version, but wanted to point that out.

**Comment by jackpot51** [comment]
@jacobgkau we need to target older kernels oto. I will add the appropriate defines to fix this.
